services:
  redis:
    container_name: frotas-redis
    healthcheck:
      interval: 5s
      retries: 5
      test: ['CMD', 'redis-cli', 'ping']
      timeout: 3s
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  sqlserver:
    container_name: frotas-sqlserver
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_PID: Developer
      MSSQL_SA_PASSWORD: ${DB_PASSWORD:-Str0ngP@ssword!}
    healthcheck:
      interval: 10s
      retries: 10
      test:
        - CMD
        - /opt/mssql-tools18/bin/sqlcmd
        - -S
        - localhost
        - -U
        - sa
        - -P
        - ${DB_PASSWORD:-Str0ngP@ssword!}
        - -Q
        - SELECT 1
        - -No
      timeout: 5s
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - '1433:1433'
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  redis_data:
  sqlserver_data:
